#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m display status                       # status of displays
      m display autobrightness [ YES | NO ]  # whether to enable the ambient light sensor to automatically darken/brighten the screen
__EOF__
}

display_status(){
    system_profiler SPDisplaysDataType
}

autobrightness() {
    osascript <<-HEREDOC
			tell application "System Preferences"
				close
				activate

				set current pane to pane "com.apple.preference.displays"
				delay 1
			end tell

			tell application "System Events"
				tell application process "System Preferences"
					repeat with theWindow in windows
						tell theWindow
							click

							tell tab group 1
								click radio button "Display"

								set theCheckbox to checkbox "Automatically adjust brightness" of group 1

								tell theCheckbox
									set checkboxStatus to value of theCheckbox as boolean

									if checkboxStatus is not $(_mcli_convert_yes_no_to_boolean "${1}") then click theCheckbox
								end tell
							end tell
						end tell
					end
				end tell
			end tell
		HEREDOC

    echo "${command} ${subcommand}: ${1}"
}

case "${subcommand}" in
    help)
        help
        ;;
    status)
        display_status
        ;;
    autobrightness)
        autobrightness "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
