#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m firewall status                            # Show status
      m firewall enable                            # Enable firewall
      m firewall disable                           # Disable firewall
      m firewall list                              # List applications handled by firewall
      m firewall autoallowsignedapps  [ YES | NO ] # Whether to allow signed applications automatically
      m firewall blockall             [ YES | NO ] # Whether to block all incoming connections
      m firewall logging              [ YES | NO ] # Whether to enable firewall logging
      m firewall stealth              [ YES | NO ] # Whether to respond to pings
      m firewall add /path/to/file                 # Add app to firewall
      m firewall remove /path/to/file              # Remove app from firewall
__EOF__
}

case "${subcommand}" in
    help)
        help
        ;;
    status)
        value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate)"

        echo "${command} ${subcommand}: ${value}"
        ;;
    enable)
        value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on)"

        echo "${command} ${subcommand}: ${value}"
        ;;
    disable)
        value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off)"

        echo "${command} ${subcommand}: ${value}"
        ;;
    autoallowsignedapps)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        if [ -n "${choice}" ]; then
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned    "${choice}")"
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsignedapp "${choice}")"
        else
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getallowsigned)"
        fi

        echo "${command} ${subcommand}: ${value}"
        ;;
    blockall)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        if [ -n "${choice}" ]; then
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setblockall "${choice}")"
        else
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getblockall)"
        fi

        echo "${command} ${subcommand}: ${value}"
        ;;
    logging)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        if [ -n "${choice}" ]; then
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode "${choice}")"
        else
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getloggingmode)"
        fi

        echo "${command} ${subcommand}: ${value}"
        ;;
    stealth)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        if [ -n "${choice}" ]; then
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode "${choice}")"
        else
            value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getstealthmode)"
        fi

        echo "${command} ${subcommand}: ${value}"
        ;;
    list)
        value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --list)"

        echo "${command} ${subcommand}: ${value}"
        ;;
    add)
        [ -z "$2" ] && help && exit 1
          value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "$2")"

        echo "${command} ${subcommand}: ${value}"
        ;;
    remove)
        [ -z "$2" ] && help && exit 1
        value="$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --remove "$2")"

        echo "${command} ${subcommand}: ${value}"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
