#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m keychain locking  [ YES | NO ] x  # Whether and how long to wait before the keychain locks
__EOF__
}

locking() {
    local choice="$(_mcli_convert_yes_no_to_boolean "$1")"
    local delay="$(_mcli_convert_number_to_number "$2")"

    local lockonsleep=""
    local lockontimeout=""

    if [ -n "${choice}" ]; then
        lockonsleep="-l"
    fi

    if [ -n "${delay}" ]; then
        lockontimeout="-u -t ${delay}"
    fi

    security set-keychain-settings ${lockonsleep} ${lockontimeout}

    echo "${command} ${subcommand}: ${choice} ${delay}"
}

case "${subcommand}" in
    help)
        help
        ;;
    locking)
        locking "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
