#!/usr/bin/env bash

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m logging secure    # Set various security measures
__EOF__
}

secure(){
    sudo perl -pi -e "s/> system\.log.*$/> system.log mode=0640 format=bsd rotate=utc compress file_max=5M ttl=90/g"              /etc/asl.conf
    sudo perl -pi -e "s/> system\.log.*$/> system.log mode=0640 format=bsd rotate=utc compress file_max=5M ttl=90/g"              /etc/asl.conf
    sudo perl -pi -e "s-/var/log/install.log-/var/log/install.log mode=0640 format=bsd rotate=utc compress file_max=5M ttl=365-g" /etc/asl/com.apple.install

    sudo sh -c "echo '* file /var/log/authd.log mode=0640 format=bsd rotate=utc compress file_max=5Mttl=90' >> /etc/asl.conf"

    echo "${command} ${subcommand}"
}

case "${subcommand}" in
    help)
        help
        ;;
    secure)
        secure
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
