#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m mail urlloading               [ ON | OFF ]    # whether to automatically load images and other URLs
      m mail junkmailfiltering        [ ON | OFF ]    # whether to use Mail's junk filtering
      m mail messageencryption        [ ON | OFF ]    # whether to encrypt email automatically if a public key for the address exists
      m mail messagesigning           [ ON | OFF ]    # whether to sign all emails automatically
      m mail draftencryption          [ ON | OFF ]    # whether to encrypt email drafts automatically

      m mail showunreadmessagesinbold [ YES | NO ]    # whether to show unread message subjects in bold fonts
      m mail showcontactphotos        [ YES | NO ]    # whether to show photos next to messages

      m mail numberoflinesinpreview   x               # the number of message body lines to display in the message list
      m mail conversationsortorder    [ asc | desc ]  # whether to show the newest or oldest conversation at the top
__EOF__

}

urlloading(){
    value="$(_mcli_defaults_yes_no_to_inverted_boolean "com.apple.mail-shared" \
                                                       "DisableURLLoading" \
                                                       "$1")"

    echo "${command} ${subcommand}: ${value}"
}

junkmailfiltering(){
    choice="$(_mcli_convert_yes_no_to_integer "$1")"

    [[ "${choice}" == "1" ]] && choice="2"

    value="$(_mcli_defaults_number "com.apple.mail" \
                                   "JunkMailBehavior" \
                                   "${choice}")"

    echo "${command} ${subcommand}: ${value}"
}

messageencryption(){
    value="$(_mcli_defaults_yes_no_to_boolean "org.gpgtools.gpgmail" \
                                              "EncryptNewEmailsByDefault" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

messagesigning(){
    value="$(_mcli_defaults_yes_no_to_boolean "org.gpgtools.gpgmail" \
                                              "SignNewEmailsByDefault" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

draftencryption(){
    value="$(_mcli_defaults_yes_no_to_boolean "org.gpgtools.gpgmail" \
                                              "OptionallyEncryptDrafts" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

showunreadmessagesinbold(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.mail" \
                                              "ShouldShowUnreadMessagesInBold" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

numberoflinesinpreview(){
    value="$(_mcli_defaults_yes_no_to_integer "com.apple.mail" \
                                              "NumberOfSnippetLines" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

conversationsortorder(){
    choice="$(if [[ "$1" == "asc" ]]; then echo "NO"; elif [[ "$1" == "desc" ]]; then echo "YES"; fi)"
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.mail" \
                                              "ConversationViewSortDescending" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

showcontactphotos(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.mail" \
                                              "EnableContactPhotos" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    urlloading)
        urlloading "$@"
        ;;
    junkmailfiltering)
        junkmailfiltering "$@"
        ;;
    messageencryption)
        messageencryption "$@"
        ;;
    messagesigning)
        messagesigning "$@"
        ;;
    draftencryption)
        draftencryption "$@"
        ;;
    showunreadmessagesinbold)
        showunreadmessagesinbold "$@"
        ;;
    numberoflinesinpreview)
        numberoflinesinpreview "$@"
        ;;
    conversationsortorder)
        conversationsortorder "$@"
        ;;
    showcontactphotos)
        showcontactphotos "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
