#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m screensaver                                                                   # launch screensaver
      m screensaver status                                                            # get the current status
      m screensaver askforpassword [ YES | NO ]                                       # whether to enable password requirement to unlock
      m screensaver passworddelay  [ "immediately" | "5 seconds" | "1 minute" | etc ] # the length of time before screensaver requires password
__EOF__
}

askforpassword(){
    value="$(_mcli_defaults_yes_no_to_integer "com.apple.screensaver" \
                                              "askForPassword" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

passworddelay(){
    osascript <<-HEREDOC
			tell application "System Preferences"
				close
				activate

				set current pane to pane "com.apple.preference.security"
				delay 1
			end tell

			tell application "System Events"
				tell application process "System Preferences"
					tell tab group 1 of window "Security & Privacy"
						click radio button "General"

						click pop up button 1

						tell pop up button 1
							click menu item "${1}" of menu 1
						end tell
					end tell
				end tell
			end tell
		HEREDOC

    echo "${command} ${subcommand}: ${1}"
}

status(){
    local value=$(osascript -e 'tell application "System Events"' \
                            -e 'get running of screen saver preferences' \
                            -e 'end tell')

    value="$(_mcli_convert_yes_no_to_enabled_disabled "${value}")"

    echo "${command}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    askforpassword)
        askforpassword "$@"
        ;;
    passworddelay)
        passworddelay "$@"
        ;;
    status)
        status
        ;;
    *)
        open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
