#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m security certificatechecking               [ YES | NO ]  # Whether to verify if certificates have been revoked
      m security adminauthorizationforpreferences  [ YES | NO ]  # Whether an administrators credentials is required for preference changes
__EOF__
}

certificatechecking() {
    choice="$(_mcli_convert_yes_no_to_boolean "$1")"

    if [[ "${choice}" == "true" ]]; then
        value="$(_mcli_defaults_string "com.apple.security.revocation" \
                                       "CRLStyle" \
                                       "RequireIfPresent")"

        value="$(_mcli_defaults_string "com.apple.security.revocation" \
                                       "OCSPStyle" \
                                       "RequireIfPresent")"
    else
        value="$(_mcli_defaults_delete "com.apple.security.revocation" \
                                       "CRLStyle")"

        value="$(_mcli_defaults_delete "com.apple.security.revocation" \
                                       "OCSPStyle")"
    fi

    echo "${command} ${subcommand}: ${value}"
}

adminauthorizationforpreferences() {
    osascript <<-HEREDOC
			tell application "System Preferences"
				close
				activate

				set current pane to pane "com.apple.preference.security"
				delay 1
			end tell

			tell application "System Events"
				tell application process "System Preferences"
					tell window "Security & Privacy"
						click button "Advanced…"

						tell sheet 1
							set theCheckbox to checkbox "Require an administrator password to access system-wide preferences"

							tell theCheckbox
								set checkboxStatus to value of theCheckbox as boolean

								if checkboxStatus is not $(_mcli_convert_yes_no_to_boolean "${1}") then click theCheckbox
							end tell

							click button "OK"
						end tell
					end tell
				end tell
			end tell
		HEREDOC

    echo "${command} ${subcommand}: ${1}"
}

case "${subcommand}" in
    help)
        help
        ;;
    certificatechecking)
        certificatechecking "$@"
        ;;
    adminauthorizationforpreferences)
        adminauthorizationforpreferences "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
