#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m windows doubleclickaction [ "minimize" | "zoom" ] # What action to take when double-clicking a window's title bar

__EOF__
}

doubleclickaction() {
    value="$(_mcli_defaults_string "NSGlobalDomain" \
                                   "AppleActionOnDoubleClick" \
                                   "$(_mcli_convert_string_to_initial_capital "$1")")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    doubleclickaction)
        doubleclickaction "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
